### ISSUE TITLE
Update Dgraph Schema

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#266] opened 2020-10-27 22:03 UTC
## Expected Behaviour

Sibling of issue #257. 
- Granular types for each level of the UC product hierarchy (proposal to mirror the GQL schema types in linked issue, excluding GQL specific fields, e.g. interactions/sorting/searching)

## Current Behaviour

- Entity/Property types only

## Possible Solution

- Update schema.gql with V2 of schema definition (using Dgraph's type system rather than a field of `type` on an `Entity` node)
- Update demo.json with a couple of test products to get started

**Comment by wlthomson** [comment] 2020-11-02 01:36
@katherine-sussol

![uhoh](https://user-images.githubusercontent.com/43223637/97821844-b7806e00-1d18-11eb-93cb-7841947f6f0c.gif)

**Comment by wlthomson** [comment] 2020-11-04 22:20
@katherine-sussol OK if I close this as a duplicate of #257?

![sorry](https://user-images.githubusercontent.com/43223637/98173955-e4bb5f00-1f58-11eb-80bb-b0b9616cb575.gif)

**Comment by katherine-sussol** [comment] 2020-11-04 22:23
Sure - does this mean #257 will include both Dgraph and Apollo Server Schema changes?

**Comment by wlthomson** [comment] 2020-11-04 23:29
> > @katherine-sussol OK if I close this as a duplicate of #257?
> 
> Sure - does this mean #257 will include both Dgraph and Apollo Server Schema changes?

Hmm, good point. Should we have this issue for the Dgraph changes and #257 for the server-side changes?

**Comment by katherine-sussol** [comment] 2020-11-04 23:46
Either works, although I think having them split up may encourage smaller PRs/discussions 😼 , so would lean towards keeping this issue for Dgraph and the other for Apollo Server/GraphQL

**Comment by wlthomson** [comment] 2020-12-02 22:19
Fixed by #270.

**Closed** 2020-12-02 22:19 UTC
Labels: data-service
