### ISSUE TITLE
Synonyms are not displayed

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/unified-codes#314] opened 2021-02-15 05:19 UTC
Currently synonyms are neither imported nor displayed

## Expected Behaviour
List the synonyms somewhere.
Search synonym values as well as the current description

**Comment by DhanyaHerath** [comment] 2021-05-17 05:35
Duplicate of https://github.com/openmsupply/unified-codes/issues/339

**Closed by DhanyaHerath** 2021-05-17 05:35 UTC
Labels: data-service, web

**Comment by mark-prins** [comment] 2021-05-17 21:55
> Duplicate of #339

But that one is about 'common names' and this one is for 'synonyms' and those are.. oh, wait.
